@MyOldApi_HostAddress = http://localhost:5145

GET {{MyOldApi_HostAddress}}/teams/
Accept: application/json

###

GET {{MyOldApi_HostAddress}}/teams/1
Accept: application/json

###

GET {{MyOldApi_HostAddress}}/teams/2/players/12
Accept: application/json

###
