// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnackBarPOS.Api.Data;

#nullable disable

namespace SnackBarPOS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522214329_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Frituur snacks",
                            IconEmoji = "🍟",
                            IsActive = true,
                            Name = "Snacks",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Broodjes en sandwiches",
                            IconEmoji = "🥪",
                            IsActive = true,
                            Name = "Broodjes",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Koffie, thee en chocolademelk",
                            IconEmoji = "☕",
                            IsActive = true,
                            Name = "Warme Dranken",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Koude dranken",
                            IconEmoji = "🥤",
                            IsActive = true,
                            Name = "Frisdranken",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Snoep, koekjes en gebak",
                            IconEmoji = "🍪",
                            IsActive = true,
                            Name = "Snoep & Koek",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountTendered")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kleine portie patat",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Patat Klein",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grote portie patat",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Patat Groot",
                            Price = 3.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rundvleeskroket",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Kroket",
                            Price = 2.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Klassieke frikandel",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Frikandel",
                            Price = 1.80m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6 stuks bitterballen",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Bitterballen (6 st)",
                            Price = 4.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kaassoufflé",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Kaassoufflé",
                            Price = 2.20m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grote loempia",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Loempia",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kipcorn",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Kipcorn",
                            Price = 2.30m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Broodje met kroket",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Broodje Kroket",
                            Price = 3.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Broodje met frikandel",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Broodje Frikandel",
                            Price = 3.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Broodje belegen kaas",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Broodje Kaas",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Broodje met salade, ei en tomaat",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Broodje Gezond",
                            Price = 4.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Verse koffie",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Koffie",
                            Price = 2.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cappuccino",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Cappuccino",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thee naar keuze",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Thee",
                            Price = 1.80m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warme chocolademelk",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Chocolademelk",
                            Price = 2.20m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Coca-Cola 330ml",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Cola",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fanta Orange 330ml",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Fanta",
                            Price = 2.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bruisend water 330ml",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Spa Rood",
                            Price = 2.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vers appelsap 200ml",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Appelsap",
                            Price = 2.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocomel pakje 200ml",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Chocomel",
                            Price = 2.20m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ambachtelijke stroopwafel",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Stroopwafel",
                            Price = 1.00m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Punt appeltaart",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Appeltaart",
                            Price = 3.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gevulde koek met amandelspijs",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Gevulde Koek",
                            Price = 1.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocoladereep",
                            IsActive = true,
                            IsAvailable = true,
                            Name = "Chocoladereep",
                            Price = 1.50m,
                            UpdatedAt = new DateTime(2026, 5, 5, 22, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.OrderItem", b =>
                {
                    b.HasOne("SnackBarPOS.Api.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackBarPOS.Api.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Product", b =>
                {
                    b.HasOne("SnackBarPOS.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SnackBarPOS.Api.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
